server:
  port: 8084

spring:
  application:
    name: dispensing-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5436/dispensing_db}
    username: ${SPRING_DATASOURCE_USERNAME:recetaya}
    password: ${SPRING_DATASOURCE_PASSWORD:recetaya123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Misma clave que en auth-service, para poder validar el JWT que llega.
jwt:
  secret: ${JWT_SECRET:recetasyaduocclantoniovaras12345678}

# URL base para llamar a inventory-service.
inventory-service:
  base-url: ${INVENTORY_SERVICE_URL:http://localhost:8083}

# URL base para llamar a receta-service y validar la receta antes de dispensar.
receta-service:
  base-url: ${RECETA_SERVICE_URL:http://localhost:8082}