server:
  port: 8082

spring:
  application:
    name: receta-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/receta_db}
    username: ${SPRING_DATASOURCE_USERNAME:recetaya}
    password: ${SPRING_DATASOURCE_PASSWORD:recetaya123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:recetasyaduocclantoniovaras12345678}

aws:
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:http://localhost:4566}
    region: us-east-1
    queue-name: reserva-stock-queue