server:
  port: 8082

spring:
  application:
    name: receta-service
  datasource:
    url: jdbc:postgresql://localhost:5434/receta_db
    username: recetaya
    password: recetaya123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Misma clave que en auth-service, para poder validar el JWT que llega.
jwt:
  secret: recetasyaduocclantoniovaras12345678

# Cola SQS apuntando a LocalStack mientras se desarrolla en local.
aws:
  sqs:
    endpoint: http://localhost:4566
    region: us-east-1
    queue-name: reserva-stock-queue